export type Card = {
  id: string;
  deck: string;
  word: string;
  ipa: string;
  hint: string;
  translation: string;
  example: string;
  ru: string;
};
export const decks = [
  {
    id: "start",
    title: "Первые разговоры",
    icon: "chatbubbles-outline",
    color: "#C7B8FF",
  },
  {
    id: "travel",
    title: "В дороге",
    icon: "airplane-outline",
    color: "#93C5FD",
  },
  { id: "home", title: "Жильё и быт", icon: "home-outline", color: "#F7C873" },
  {
    id: "food",
    title: "Еда и покупки",
    icon: "cafe-outline",
    color: "#FFA98A",
  },
  {
    id: "work",
    title: "Работа и аналитика",
    icon: "briefcase-outline",
    color: "#91E6C5",
  },
  {
    id: "connect",
    title: "Связная речь",
    icon: "link-outline",
    color: "#F0AED9",
  },
];
// British English IPA. Cyrillic hints are deliberately approximate, never an IPA substitute.
const rows: [string, string, string, string, string, string, string][] = [
  [
    "start",
    "hello",
    "/həˈləʊ/",
    "хэ-ЛОУ",
    "привет",
    "Hello! My name is Alex.",
    "Привет! Меня зовут Алекс.",
  ],
  [
    "start",
    "please",
    "/pliːz/",
    "ПЛИИЗ",
    "пожалуйста",
    "A glass of water, please.",
    "Стакан воды, пожалуйста.",
  ],
  [
    "start",
    "thank you",
    "/ˈθæŋk juː/",
    "СЭНК* ю",
    "спасибо",
    "Thank you for your help.",
    "Спасибо за помощь.",
  ],
  [
    "start",
    "sorry",
    "/ˈsɒri/",
    "СО-ри",
    "извините / сожалею",
    "Sorry, I am late.",
    "Извините, я опоздал.",
  ],
  [
    "start",
    "understand",
    "/ˌʌndəˈstænd/",
    "ан-дэ-СТЭНД",
    "понимать",
    "I do not understand.",
    "Я не понимаю.",
  ],
  [
    "start",
    "repeat",
    "/rɪˈpiːt/",
    "ри-ПИИТ",
    "повторять",
    "Could you repeat that, please?",
    "Не могли бы вы повторить это?",
  ],
  [
    "start",
    "slowly",
    "/ˈsləʊli/",
    "СЛОУ-ли",
    "медленно",
    "Please speak slowly.",
    "Пожалуйста, говорите медленно.",
  ],
  [
    "start",
    "nice to meet you",
    "/ˌnaɪs tə ˈmiːt juː/",
    "найс тэ МИИТ ю",
    "приятно познакомиться",
    "Hi, nice to meet you!",
    "Привет, приятно познакомиться!",
  ],
  [
    "travel",
    "ticket",
    "/ˈtɪkɪt/",
    "ТИ-кит",
    "билет",
    "I need a train ticket.",
    "Мне нужен билет на поезд.",
  ],
  [
    "travel",
    "airport",
    "/ˈeəpɔːt/",
    "ЭЭ-поот",
    "аэропорт",
    "How do I get to the airport?",
    "Как добраться до аэропорта?",
  ],
  [
    "travel",
    "luggage",
    "/ˈlʌɡɪdʒ/",
    "ЛА-гидж",
    "багаж",
    "My luggage is missing.",
    "Мой багаж пропал.",
  ],
  [
    "travel",
    "passport",
    "/ˈpɑːspɔːt/",
    "ПААС-поот",
    "паспорт",
    "Here is my passport.",
    "Вот мой паспорт.",
  ],
  [
    "travel",
    "where",
    "/weə/",
    "УЭЭ*",
    "где / куда",
    "Where is the station?",
    "Где вокзал?",
  ],
  [
    "travel",
    "left",
    "/left/",
    "ЛЭФТ",
    "налево / левый",
    "Turn left at the station.",
    "Поверните налево у вокзала.",
  ],
  [
    "travel",
    "right",
    "/raɪt/",
    "РАЙТ",
    "направо / правый",
    "Turn right here.",
    "Здесь поверните направо.",
  ],
  [
    "travel",
    "help",
    "/help/",
    "ХЭЛП",
    "помощь / помогать",
    "Could you help me?",
    "Не могли бы вы мне помочь?",
  ],
  [
    "home",
    "rent",
    "/rent/",
    "РЭНТ",
    "аренда / арендовать",
    "How much is the rent?",
    "Сколько стоит аренда?",
  ],
  [
    "home",
    "flat",
    "/flæt/",
    "ФЛЭТ",
    "квартира",
    "I am looking for a flat.",
    "Я ищу квартиру.",
  ],
  [
    "home",
    "deposit",
    "/dɪˈpɒzɪt/",
    "ди-ПО-зит",
    "залог / депозит",
    "Is the deposit refundable?",
    "Залог возвращается?",
  ],
  [
    "home",
    "bill",
    "/bɪl/",
    "БИЛ",
    "счёт",
    "Are bills included?",
    "Коммунальные платежи включены?",
  ],
  [
    "home",
    "quiet",
    "/ˈkwaɪət/",
    "КУАЙ-эт",
    "тихий",
    "The neighbourhood is quiet.",
    "Район тихий.",
  ],
  [
    "home",
    "neighbour",
    "/ˈneɪbə/",
    "НЭЙ-бэ",
    "сосед",
    "My neighbour is friendly.",
    "Мой сосед дружелюбный.",
  ],
  [
    "home",
    "key",
    "/kiː/",
    "КИИ",
    "ключ",
    "I have lost my key.",
    "Я потерял ключ.",
  ],
  [
    "home",
    "available",
    "/əˈveɪləbl/",
    "э-ВЭЙ-лэ-бл",
    "доступный / свободный",
    "Is this flat available?",
    "Эта квартира свободна?",
  ],
  [
    "food",
    "water",
    "/ˈwɔːtə/",
    "УО*-тэ",
    "вода",
    "Can I have some water?",
    "Можно мне воды?",
  ],
  [
    "food",
    "coffee",
    "/ˈkɒfi/",
    "КО-фи",
    "кофе",
    "One coffee, please.",
    "Один кофе, пожалуйста.",
  ],
  [
    "food",
    "menu",
    "/ˈmenjuː/",
    "МЭН-юу",
    "меню",
    "Could I see the menu?",
    "Можно посмотреть меню?",
  ],
  [
    "food",
    "order",
    "/ˈɔːdə/",
    "ОО-дэ",
    "заказ / заказывать",
    "I would like to order.",
    "Я хотел бы сделать заказ.",
  ],
  [
    "food",
    "price",
    "/praɪs/",
    "ПРАЙС",
    "цена",
    "What is the price?",
    "Какая цена?",
  ],
  [
    "food",
    "expensive",
    "/ɪkˈspensɪv/",
    "ик-СПЭН-сив",
    "дорогой",
    "It is too expensive.",
    "Это слишком дорого.",
  ],
  [
    "food",
    "pay",
    "/peɪ/",
    "ПЭЙ",
    "платить",
    "Can I pay by card?",
    "Можно оплатить картой?",
  ],
  [
    "food",
    "receipt",
    "/rɪˈsiːt/",
    "ри-СИИТ",
    "чек",
    "Could I have a receipt?",
    "Можно мне чек?",
  ],
  [
    "work",
    "meeting",
    "/ˈmiːtɪŋ/",
    "МИИ-тинг*",
    "встреча / совещание",
    "The meeting starts at ten.",
    "Встреча начинается в десять.",
  ],
  [
    "work",
    "deadline",
    "/ˈdedlaɪn/",
    "ДЭД-лайн",
    "крайний срок",
    "What is the deadline?",
    "Какой крайний срок?",
  ],
  [
    "work",
    "revenue",
    "/ˈrevənjuː/",
    "РЭ-вэ-ньюу",
    "выручка",
    "Revenue increased last month.",
    "В прошлом месяце выручка выросла.",
  ],
  [
    "work",
    "retention",
    "/rɪˈtenʃən/",
    "ри-ТЭН-шэн",
    "удержание",
    "We need to improve retention.",
    "Нужно улучшить удержание.",
  ],
  [
    "work",
    "conversion",
    "/kənˈvɜːʃən/",
    "кэн-ВЁЁ-шэн",
    "конверсия",
    "Conversion fell by two percentage points.",
    "Конверсия снизилась на два процентных пункта.",
  ],
  [
    "work",
    "funnel",
    "/ˈfʌnəl/",
    "ФА-нэл",
    "воронка",
    "Let us analyse the funnel.",
    "Давайте проанализируем воронку.",
  ],
  [
    "work",
    "requirement",
    "/rɪˈkwaɪəmənt/",
    "ри-КУАЙ-э-мэнт",
    "требование",
    "Could you clarify this requirement?",
    "Можете уточнить это требование?",
  ],
  [
    "work",
    "experience",
    "/ɪkˈspɪəriəns/",
    "ик-СПИЭ-ри-энс",
    "опыт",
    "I have experience in analytics.",
    "У меня есть опыт в аналитике.",
  ],
  [
    "connect",
    "because",
    "/bɪˈkɒz/",
    "би-КОЗ",
    "потому что",
    "I am learning English because I want to travel.",
    "Я учу английский, потому что хочу путешествовать.",
  ],
  [
    "connect",
    "although",
    "/ɔːlˈðəʊ/",
    "оол-ЗОУ*",
    "хотя",
    "Although it is hard, I keep learning.",
    "Хотя это трудно, я продолжаю учиться.",
  ],
  [
    "connect",
    "however",
    "/haʊˈevə/",
    "хау-Э-вэ",
    "однако",
    "It is useful. However, it takes time.",
    "Это полезно. Однако это требует времени.",
  ],
  [
    "connect",
    "actually",
    "/ˈæktʃuəli/",
    "ЭК-чу-э-ли",
    "на самом деле",
    "Actually, I live in Kazakhstan.",
    "На самом деле я живу в Казахстане.",
  ],
  [
    "connect",
    "probably",
    "/ˈprɒbəbli/",
    "ПРО-бэ-бли",
    "вероятно",
    "I will probably arrive tomorrow.",
    "Вероятно, я приеду завтра.",
  ],
  [
    "connect",
    "I agree",
    "/aɪ əˈɡriː/",
    "ай э-ГРИИ",
    "я согласен",
    "I agree with you.",
    "Я с тобой согласен.",
  ],
  [
    "connect",
    "in my opinion",
    "/ɪn maɪ əˈpɪnjən/",
    "ин май э-ПИН-йэн",
    "по моему мнению",
    "In my opinion, this is a good idea.",
    "По моему мнению, это хорошая идея.",
  ],
  [
    "connect",
    "get used to",
    "/ɡet ˈjuːst tə/",
    "гэт ЮУСТ тэ",
    "привыкнуть к",
    "I need to get used to the weather.",
    "Мне нужно привыкнуть к погоде.",
  ],
];
export const cards: Card[] = rows.map(
  ([deck, word, ipa, hint, translation, example, ru], i) => ({
    id: `word-${i + 1}`,
    deck,
    word,
    ipa,
    hint,
    translation,
    example,
    ru,
  }),
);
